<!DOCTYPE html>
<html>
    <head>
        <title>Promises with Generators</title>
    </head>
    <body>

<p>(View the output in DevTools/Console)</p>

<script>
function* genFunc() {
  let user = 1;
  while (true) {
    user++;
    try {
      const response = yield fetch(`https://jsonplaceholder.typicode.com/users/${user}`);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
    } catch (error) {
      console.error('A fetch error occurred:', error);
      return; // Terminate the generator if a fetch error occurs
    }
  }
}

function run(genFunc) {
  let genObj = genFunc();

  function step(value) {
    try {
      let result = genObj.next(value);
      if (result.done) return;
      console.log(result);
      result.value.then(response => {
        console.log(response.json()); // log the actual data
        step(response);
      })
        .catch(error => {
        console.error('An error occurred:', error);
        genObj.return(); // Terminate the generator if a promise rejection occurs
      });
    } catch (error) {
      console.error('A generator error occurred:', error);
    }
  }

  step();
}

run(genFunc);
</script>

    </body>
</html>
